name: Build ytdlp-gui for aarch64

on:
  schedule:
    - cron: '0 0 1 * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout upstream repository
        uses: actions/checkout@v4
        with:
          repository: BKSalman/ytdlp-gui
          ref: main

      # Updated to v3 to fix the Node 20 warning
      - name: Build in Arch Linux ARM container
        uses: uraimo/run-on-arch-action@v3 
        with:
          arch: aarch64
          # Fixed the distribution name to Arch ARM
          distro: archarm_latest 
          githubToken: ${{ github.token }}
          run: |
            pacman -Syu --noconfirm base-devel rustup git pkgconf gtk3 cmake
            rustup toolchain install stable
            rustup default stable
            cargo build --release
            
            cp target/release/ytdlp-gui ./ytdlp-gui-aarch64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ytdlp-gui-aarch64
          path: ./ytdlp-gui-aarch64